include(FindPackageHandleStandardArgs)

pkg_search_module(PC_LIBSOUP REQUIRED libsoup-3.0 libsoup-2.4)

find_path(LIBSOUP_INCLUDE_DIR NAMES libsoup/soup.h
	HINTS ${PC_LIBSOUP_INCLUDEDIR} ${PC_LIBSOUP_INCLUDE_DIRS}
)

find_library(LIBSOUP_LIBRARY
	NAMES soup soup-3.0 soup-2.4
	HINTS ${PC_LIBSOUP_LIBDIR} ${PC_LIBSOUP_LIBRARY_DIRS}
	)

if (LIBSOUP_INCLUDE_DIR AND LIBSOUP_LIBRARY)
	find_package_handle_standard_args(LIBSOUP DEFAULT_MSG LIBSOUP_LIBRARY LIBSOUP_INCLUDE_DIR)
endif()

if (LIBSOUP_FOUND)
	set(LIBSOUP_LIBRARIES ${LIBSOUP_LIBRARY})
	set(LIBSOUP_INCLUDE_DIRS ${LIBSOUP_INCLUDE_DIR})
endif()

mark_as_advanced(LIBSOUP_INCLUDE_DIR LIBSOUP_LIBRARY)
