name: $(BuildID)

trigger:
  branches:
    include:
      - master

variables:
  - group: conan

jobs:
  - job: android
    pool:
      name: 'Devolutions - Linux containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:android

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - script: ./build.py -p android --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: linux64
    pool:
      name: 'Devolutions - Linux containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:linux

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - script: ./build.py -p linux -a x86_64 --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: iOS
    pool:
      name: 'Devolutions - macOS'

    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - script: ./build.py -p ios --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: macOS
    pool:
      name: 'Devolutions - macOS'

    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - script: ./build.py -p macos --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: windows
    pool:
      name: 'Devolutions - Windows containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:vstools2k19

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - script: C:\BuildTools\Common7\Tools\VsDevCmd.bat && python build.py -p windows --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)
