name: $(BuildID)

trigger:
  branches:
    include:
      - master

variables:
  - group: conan

jobs:
  - job: windows
    pool:
      name: 'Devolutions - Windows containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:vstools2k19

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - powershell: python build.py -p windows
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)