name: $(BuildID)

trigger:
  branches:
    include:
      - master

variables:
  - group: conan

jobs:
  - job: android
    pool:
      name: 'Devolutions - Linux containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:android

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          hostName: 'bitbucket.org,18.205.93.0 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCbGwdwKbg5PidSqxq4rgPVEAop/9sh138GGgcJLISQOZQjcF1HcdzEkx0HmE5wsjh+McfsdZdTCURbIAkEira1wAv4BpdzBHOdAIYnXu+5kHh8dpaB7c4df+w7F4tQdY10ZI+/aVuYoJw7SAb7+oBSyCtwmWmpB4hCK0MIrleUykoMfrdLbM4b3gbh8n+dhMuVfFtpZpEgkwA37240c9Bi+hE89QjeP1B4bSuUmX9/CSLb9eP1+IgcxqCe0I5q+V4h3AZQysBsO6FcTMxCCKSqWFUbikhga50uG2mGEXMHFisc566pSE1h8NEgJ2ITc67VE4nWgvgxfguK2nfGKEsjVdCIT32oiugPak9bU9DiLN6vHi5XFeyFdTRqm5lm4qPaCky77LNau1UAAitduJl7DdKfWnWlzpQZmzN5kIIfaBgxDrtqBxgKbH0QuUgLVugN94vPq+jO3ciZBuG3RAvrvMtTGJ/GdSe2PDuKH8YZRs0sHFVpuYTThhi14nMdPeEI+FxXNm2yP7WUailT5fz9WqRsghdjGTDOpa/RouOxlGZUOTG13Y/BGb/Av0HSg9sg838MQpVWZQGsIk2oUgveo+udgrLuX6ftj2nneZVxpIpKfHMfUcIyeU/DJZk8WboFUThmhhSz49x4ltsX7gNsLJVd+DKbwXuepFG8MHBwUnJ7Q2tjVvHroZ1/TPYTliGWaDVRaff1czCVIlwj2sFKvteWlgkr65e6bMu6/PyFk6zibYVo9SSfbyqFjBU2f6uznHNH0YUXG20V9dUiODCRCsEriGrCoh8A1KyElCJGpGHovxTC1pcu15g5B2wUfIM/ypfzcs1EjfkP0RbNkQx+O6YDidc8Wfprwf3K79oVcyWhlCP2fWUbK982CRiHG49FvtD6YkGP910uz2IGSV/cDj9idl2RYEFiDHjJnk4QVtAPvO8RWd9ky/3WcMPY+H6iuJp3Cbam6tkzc0VDQ26WE/rSHEukRGkk95V6teifxdAJkup0JJJatoMlDMwxghZCcVSne3w2UKD9HpgJwPbggmmairUY0tz6omoprJyR0GSCeaccG73jlgWhSKNOr77abqx3/dZM66pL0NSry4XofcfM03ycoEB6mwqA9xj28QtaW1KC/tnvAJthLaD0uuONsxpBQmw8YYLgUlXluJfZjrGw0OH+sJW7ot02sbMUexeEHwKrbr2waGd2s3m+6CVDQlFK70YF5ZSLP00g9HE7GoKJTmOi/OkbSZ17OSJT4RiW5/NhIHM4woPCqQge2IUOLwWTi3ZTpY0xZzqifCRXe3sR5YKm2vSxJxO1MVViBftB5kcBJ02GJtAdJKUI+FjxXfmvM6O7z7WaveQRKTYT azure pipelines'
          sshKeySecureFile: ssh-azp-private

      - script: ./build.py -p android --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: linux64
    pool:
      name: 'Devolutions - Linux containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:linux

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          hostName: 'bitbucket.org,18.205.93.0 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCbGwdwKbg5PidSqxq4rgPVEAop/9sh138GGgcJLISQOZQjcF1HcdzEkx0HmE5wsjh+McfsdZdTCURbIAkEira1wAv4BpdzBHOdAIYnXu+5kHh8dpaB7c4df+w7F4tQdY10ZI+/aVuYoJw7SAb7+oBSyCtwmWmpB4hCK0MIrleUykoMfrdLbM4b3gbh8n+dhMuVfFtpZpEgkwA37240c9Bi+hE89QjeP1B4bSuUmX9/CSLb9eP1+IgcxqCe0I5q+V4h3AZQysBsO6FcTMxCCKSqWFUbikhga50uG2mGEXMHFisc566pSE1h8NEgJ2ITc67VE4nWgvgxfguK2nfGKEsjVdCIT32oiugPak9bU9DiLN6vHi5XFeyFdTRqm5lm4qPaCky77LNau1UAAitduJl7DdKfWnWlzpQZmzN5kIIfaBgxDrtqBxgKbH0QuUgLVugN94vPq+jO3ciZBuG3RAvrvMtTGJ/GdSe2PDuKH8YZRs0sHFVpuYTThhi14nMdPeEI+FxXNm2yP7WUailT5fz9WqRsghdjGTDOpa/RouOxlGZUOTG13Y/BGb/Av0HSg9sg838MQpVWZQGsIk2oUgveo+udgrLuX6ftj2nneZVxpIpKfHMfUcIyeU/DJZk8WboFUThmhhSz49x4ltsX7gNsLJVd+DKbwXuepFG8MHBwUnJ7Q2tjVvHroZ1/TPYTliGWaDVRaff1czCVIlwj2sFKvteWlgkr65e6bMu6/PyFk6zibYVo9SSfbyqFjBU2f6uznHNH0YUXG20V9dUiODCRCsEriGrCoh8A1KyElCJGpGHovxTC1pcu15g5B2wUfIM/ypfzcs1EjfkP0RbNkQx+O6YDidc8Wfprwf3K79oVcyWhlCP2fWUbK982CRiHG49FvtD6YkGP910uz2IGSV/cDj9idl2RYEFiDHjJnk4QVtAPvO8RWd9ky/3WcMPY+H6iuJp3Cbam6tkzc0VDQ26WE/rSHEukRGkk95V6teifxdAJkup0JJJatoMlDMwxghZCcVSne3w2UKD9HpgJwPbggmmairUY0tz6omoprJyR0GSCeaccG73jlgWhSKNOr77abqx3/dZM66pL0NSry4XofcfM03ycoEB6mwqA9xj28QtaW1KC/tnvAJthLaD0uuONsxpBQmw8YYLgUlXluJfZjrGw0OH+sJW7ot02sbMUexeEHwKrbr2waGd2s3m+6CVDQlFK70YF5ZSLP00g9HE7GoKJTmOi/OkbSZ17OSJT4RiW5/NhIHM4woPCqQge2IUOLwWTi3ZTpY0xZzqifCRXe3sR5YKm2vSxJxO1MVViBftB5kcBJ02GJtAdJKUI+FjxXfmvM6O7z7WaveQRKTYT azure pipelines'
          sshKeySecureFile: ssh-azp-private

      - script: sudo apt-get -y install libcups2-dev

      - script: ./build.py -p linux -a x86_64 --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: iOS
    pool:
      name: 'Devolutions - macOS'

    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          hostName: 'bitbucket.org,18.205.93.0 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCbGwdwKbg5PidSqxq4rgPVEAop/9sh138GGgcJLISQOZQjcF1HcdzEkx0HmE5wsjh+McfsdZdTCURbIAkEira1wAv4BpdzBHOdAIYnXu+5kHh8dpaB7c4df+w7F4tQdY10ZI+/aVuYoJw7SAb7+oBSyCtwmWmpB4hCK0MIrleUykoMfrdLbM4b3gbh8n+dhMuVfFtpZpEgkwA37240c9Bi+hE89QjeP1B4bSuUmX9/CSLb9eP1+IgcxqCe0I5q+V4h3AZQysBsO6FcTMxCCKSqWFUbikhga50uG2mGEXMHFisc566pSE1h8NEgJ2ITc67VE4nWgvgxfguK2nfGKEsjVdCIT32oiugPak9bU9DiLN6vHi5XFeyFdTRqm5lm4qPaCky77LNau1UAAitduJl7DdKfWnWlzpQZmzN5kIIfaBgxDrtqBxgKbH0QuUgLVugN94vPq+jO3ciZBuG3RAvrvMtTGJ/GdSe2PDuKH8YZRs0sHFVpuYTThhi14nMdPeEI+FxXNm2yP7WUailT5fz9WqRsghdjGTDOpa/RouOxlGZUOTG13Y/BGb/Av0HSg9sg838MQpVWZQGsIk2oUgveo+udgrLuX6ftj2nneZVxpIpKfHMfUcIyeU/DJZk8WboFUThmhhSz49x4ltsX7gNsLJVd+DKbwXuepFG8MHBwUnJ7Q2tjVvHroZ1/TPYTliGWaDVRaff1czCVIlwj2sFKvteWlgkr65e6bMu6/PyFk6zibYVo9SSfbyqFjBU2f6uznHNH0YUXG20V9dUiODCRCsEriGrCoh8A1KyElCJGpGHovxTC1pcu15g5B2wUfIM/ypfzcs1EjfkP0RbNkQx+O6YDidc8Wfprwf3K79oVcyWhlCP2fWUbK982CRiHG49FvtD6YkGP910uz2IGSV/cDj9idl2RYEFiDHjJnk4QVtAPvO8RWd9ky/3WcMPY+H6iuJp3Cbam6tkzc0VDQ26WE/rSHEukRGkk95V6teifxdAJkup0JJJatoMlDMwxghZCcVSne3w2UKD9HpgJwPbggmmairUY0tz6omoprJyR0GSCeaccG73jlgWhSKNOr77abqx3/dZM66pL0NSry4XofcfM03ycoEB6mwqA9xj28QtaW1KC/tnvAJthLaD0uuONsxpBQmw8YYLgUlXluJfZjrGw0OH+sJW7ot02sbMUexeEHwKrbr2waGd2s3m+6CVDQlFK70YF5ZSLP00g9HE7GoKJTmOi/OkbSZ17OSJT4RiW5/NhIHM4woPCqQge2IUOLwWTi3ZTpY0xZzqifCRXe3sR5YKm2vSxJxO1MVViBftB5kcBJ02GJtAdJKUI+FjxXfmvM6O7z7WaveQRKTYT azure pipelines'
          sshKeySecureFile: ssh-azp-private

      - script: ./build.py -p ios --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: macOS
    pool:
      name: 'Devolutions - macOS'

    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          hostName: 'bitbucket.org,18.205.93.0 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCbGwdwKbg5PidSqxq4rgPVEAop/9sh138GGgcJLISQOZQjcF1HcdzEkx0HmE5wsjh+McfsdZdTCURbIAkEira1wAv4BpdzBHOdAIYnXu+5kHh8dpaB7c4df+w7F4tQdY10ZI+/aVuYoJw7SAb7+oBSyCtwmWmpB4hCK0MIrleUykoMfrdLbM4b3gbh8n+dhMuVfFtpZpEgkwA37240c9Bi+hE89QjeP1B4bSuUmX9/CSLb9eP1+IgcxqCe0I5q+V4h3AZQysBsO6FcTMxCCKSqWFUbikhga50uG2mGEXMHFisc566pSE1h8NEgJ2ITc67VE4nWgvgxfguK2nfGKEsjVdCIT32oiugPak9bU9DiLN6vHi5XFeyFdTRqm5lm4qPaCky77LNau1UAAitduJl7DdKfWnWlzpQZmzN5kIIfaBgxDrtqBxgKbH0QuUgLVugN94vPq+jO3ciZBuG3RAvrvMtTGJ/GdSe2PDuKH8YZRs0sHFVpuYTThhi14nMdPeEI+FxXNm2yP7WUailT5fz9WqRsghdjGTDOpa/RouOxlGZUOTG13Y/BGb/Av0HSg9sg838MQpVWZQGsIk2oUgveo+udgrLuX6ftj2nneZVxpIpKfHMfUcIyeU/DJZk8WboFUThmhhSz49x4ltsX7gNsLJVd+DKbwXuepFG8MHBwUnJ7Q2tjVvHroZ1/TPYTliGWaDVRaff1czCVIlwj2sFKvteWlgkr65e6bMu6/PyFk6zibYVo9SSfbyqFjBU2f6uznHNH0YUXG20V9dUiODCRCsEriGrCoh8A1KyElCJGpGHovxTC1pcu15g5B2wUfIM/ypfzcs1EjfkP0RbNkQx+O6YDidc8Wfprwf3K79oVcyWhlCP2fWUbK982CRiHG49FvtD6YkGP910uz2IGSV/cDj9idl2RYEFiDHjJnk4QVtAPvO8RWd9ky/3WcMPY+H6iuJp3Cbam6tkzc0VDQ26WE/rSHEukRGkk95V6teifxdAJkup0JJJatoMlDMwxghZCcVSne3w2UKD9HpgJwPbggmmairUY0tz6omoprJyR0GSCeaccG73jlgWhSKNOr77abqx3/dZM66pL0NSry4XofcfM03ycoEB6mwqA9xj28QtaW1KC/tnvAJthLaD0uuONsxpBQmw8YYLgUlXluJfZjrGw0OH+sJW7ot02sbMUexeEHwKrbr2waGd2s3m+6CVDQlFK70YF5ZSLP00g9HE7GoKJTmOi/OkbSZ17OSJT4RiW5/NhIHM4woPCqQge2IUOLwWTi3ZTpY0xZzqifCRXe3sR5YKm2vSxJxO1MVViBftB5kcBJ02GJtAdJKUI+FjxXfmvM6O7z7WaveQRKTYT azure pipelines'
          sshKeySecureFile: ssh-azp-private

      - script: ./build.py -p macos --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: windows
    pool:
      name: 'Devolutions - Windows containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:vstools2k19

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          hostName: 'bitbucket.org,18.205.93.0 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCbGwdwKbg5PidSqxq4rgPVEAop/9sh138GGgcJLISQOZQjcF1HcdzEkx0HmE5wsjh+McfsdZdTCURbIAkEira1wAv4BpdzBHOdAIYnXu+5kHh8dpaB7c4df+w7F4tQdY10ZI+/aVuYoJw7SAb7+oBSyCtwmWmpB4hCK0MIrleUykoMfrdLbM4b3gbh8n+dhMuVfFtpZpEgkwA37240c9Bi+hE89QjeP1B4bSuUmX9/CSLb9eP1+IgcxqCe0I5q+V4h3AZQysBsO6FcTMxCCKSqWFUbikhga50uG2mGEXMHFisc566pSE1h8NEgJ2ITc67VE4nWgvgxfguK2nfGKEsjVdCIT32oiugPak9bU9DiLN6vHi5XFeyFdTRqm5lm4qPaCky77LNau1UAAitduJl7DdKfWnWlzpQZmzN5kIIfaBgxDrtqBxgKbH0QuUgLVugN94vPq+jO3ciZBuG3RAvrvMtTGJ/GdSe2PDuKH8YZRs0sHFVpuYTThhi14nMdPeEI+FxXNm2yP7WUailT5fz9WqRsghdjGTDOpa/RouOxlGZUOTG13Y/BGb/Av0HSg9sg838MQpVWZQGsIk2oUgveo+udgrLuX6ftj2nneZVxpIpKfHMfUcIyeU/DJZk8WboFUThmhhSz49x4ltsX7gNsLJVd+DKbwXuepFG8MHBwUnJ7Q2tjVvHroZ1/TPYTliGWaDVRaff1czCVIlwj2sFKvteWlgkr65e6bMu6/PyFk6zibYVo9SSfbyqFjBU2f6uznHNH0YUXG20V9dUiODCRCsEriGrCoh8A1KyElCJGpGHovxTC1pcu15g5B2wUfIM/ypfzcs1EjfkP0RbNkQx+O6YDidc8Wfprwf3K79oVcyWhlCP2fWUbK982CRiHG49FvtD6YkGP910uz2IGSV/cDj9idl2RYEFiDHjJnk4QVtAPvO8RWd9ky/3WcMPY+H6iuJp3Cbam6tkzc0VDQ26WE/rSHEukRGkk95V6teifxdAJkup0JJJatoMlDMwxghZCcVSne3w2UKD9HpgJwPbggmmairUY0tz6omoprJyR0GSCeaccG73jlgWhSKNOr77abqx3/dZM66pL0NSry4XofcfM03ycoEB6mwqA9xj28QtaW1KC/tnvAJthLaD0uuONsxpBQmw8YYLgUlXluJfZjrGw0OH+sJW7ot02sbMUexeEHwKrbr2waGd2s3m+6CVDQlFK70YF5ZSLP00g9HE7GoKJTmOi/OkbSZ17OSJT4RiW5/NhIHM4woPCqQge2IUOLwWTi3ZTpY0xZzqifCRXe3sR5YKm2vSxJxO1MVViBftB5kcBJ02GJtAdJKUI+FjxXfmvM6O7z7WaveQRKTYT azure pipelines'
          sshKeySecureFile: ssh-azp-private

      - script: C:\BuildTools\Common7\Tools\VsDevCmd.bat && python build.py -p windows --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)
