name: $(BuildID)

trigger:
  branches:
    include:
      - master

variables:
  - group: conan

jobs:
  - job: linux
    timeoutInMinutes: 300
    pool:
      name: 'Devolutions - Linux containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:linux

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - script: ./build.py -p linux -a x86_64
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: macOS
    timeoutInMinutes: 300
    pool:
      name: 'Devolutions - macOS'

    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - script: ./build.py -p macos -a x86_64
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: windows
    timeoutInMinutes: 300
    pool:
      name: 'Devolutions - Windows containers'

    workspace:
      clean: all

    container:
      image: devolutions/waykbuilder:vstools2k19
      options: --storage-opt size=128G

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - powershell: python build.py -p windows -a x86_64
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)
