name: $(BuildID)

trigger:
  branches:
    include:
      - master

variables:
  - group: conan

jobs:
  - job: android
    pool:
      name: 'Devolutions - Linux containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:android

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDh1m1BXRO0oUWEsTt2THFUqN1v4wwaNdcfKpPTpS501150EPsCCcf7BS4aFwgYl/UYMRxmywqlwQwIjmkxqdNHejYXaBa4JMDFMinWAPKLueo8xQdfcgS1xhTGdqyGFsHtjGlJMe8oys3FtK06NL6JnFHrYzVr9aR4yhMDnQyHSEHrHj+uc0OzTKnmkiG4pP3IJfnj6/HS+zLdkqs28sTAouV1YGLK34SsspCy4R5wpOMkM/6/DItqFPvdMaAPMpD52YYzyYUOVy43X8XBbLQI2hzv2lFH0enNiY3UaGKYeDL4cxzbsIenc/4WtD1HvIX9apA2fbuGqfUrk2faHkR9P7A2Eo0sbt43SY4MKBrLXlYQVDd3SFbwoDVIWgVoqrPZJmJdzKOlXgKyB9oSYdHiJkmijBFno9PWeyuHeldmw+YjUkltyD5TEcDsNd98V/EC9Mq5zTrdd1Sbaw313jlyz0uhh/lbbI0aZy8/IQries0RHmxYvPMZc4ZZA+eEcaUtJZ8ABJLIO4I+6WX/YzNJvjSV41GbBiKigUG9OeOoW3uOuFNkTXmI8DL/MXvn/6xd8hQ10qOQGVqrQ3iIffCgyG3M+v2OLVWzLxa1CQQbZFYOH5jihaKxN37Q3mrwUlSKU3vyFzrcRhbiuPDd32YZyWlAaoH0bl8+flVLMyMprw== bot@devolutions.net'
          sshPassphrase: $(SSH_AZP_PRIVATE_GITHUB_PASSPHRASE)
          sshKeySecureFile: ssh-azp-private-github


      - script: ./build.py -p android --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: linux
    pool:
      name: 'Devolutions - Linux containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:linux

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDh1m1BXRO0oUWEsTt2THFUqN1v4wwaNdcfKpPTpS501150EPsCCcf7BS4aFwgYl/UYMRxmywqlwQwIjmkxqdNHejYXaBa4JMDFMinWAPKLueo8xQdfcgS1xhTGdqyGFsHtjGlJMe8oys3FtK06NL6JnFHrYzVr9aR4yhMDnQyHSEHrHj+uc0OzTKnmkiG4pP3IJfnj6/HS+zLdkqs28sTAouV1YGLK34SsspCy4R5wpOMkM/6/DItqFPvdMaAPMpD52YYzyYUOVy43X8XBbLQI2hzv2lFH0enNiY3UaGKYeDL4cxzbsIenc/4WtD1HvIX9apA2fbuGqfUrk2faHkR9P7A2Eo0sbt43SY4MKBrLXlYQVDd3SFbwoDVIWgVoqrPZJmJdzKOlXgKyB9oSYdHiJkmijBFno9PWeyuHeldmw+YjUkltyD5TEcDsNd98V/EC9Mq5zTrdd1Sbaw313jlyz0uhh/lbbI0aZy8/IQries0RHmxYvPMZc4ZZA+eEcaUtJZ8ABJLIO4I+6WX/YzNJvjSV41GbBiKigUG9OeOoW3uOuFNkTXmI8DL/MXvn/6xd8hQ10qOQGVqrQ3iIffCgyG3M+v2OLVWzLxa1CQQbZFYOH5jihaKxN37Q3mrwUlSKU3vyFzrcRhbiuPDd32YZyWlAaoH0bl8+flVLMyMprw== bot@devolutions.net'
          sshPassphrase: $(SSH_AZP_PRIVATE_GITHUB_PASSPHRASE)
          sshKeySecureFile: ssh-azp-private-github

      - script: ./build.py -p linux -a x86_64 --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: iOS
    pool:
      name: 'Devolutions - macOS'

    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDh1m1BXRO0oUWEsTt2THFUqN1v4wwaNdcfKpPTpS501150EPsCCcf7BS4aFwgYl/UYMRxmywqlwQwIjmkxqdNHejYXaBa4JMDFMinWAPKLueo8xQdfcgS1xhTGdqyGFsHtjGlJMe8oys3FtK06NL6JnFHrYzVr9aR4yhMDnQyHSEHrHj+uc0OzTKnmkiG4pP3IJfnj6/HS+zLdkqs28sTAouV1YGLK34SsspCy4R5wpOMkM/6/DItqFPvdMaAPMpD52YYzyYUOVy43X8XBbLQI2hzv2lFH0enNiY3UaGKYeDL4cxzbsIenc/4WtD1HvIX9apA2fbuGqfUrk2faHkR9P7A2Eo0sbt43SY4MKBrLXlYQVDd3SFbwoDVIWgVoqrPZJmJdzKOlXgKyB9oSYdHiJkmijBFno9PWeyuHeldmw+YjUkltyD5TEcDsNd98V/EC9Mq5zTrdd1Sbaw313jlyz0uhh/lbbI0aZy8/IQries0RHmxYvPMZc4ZZA+eEcaUtJZ8ABJLIO4I+6WX/YzNJvjSV41GbBiKigUG9OeOoW3uOuFNkTXmI8DL/MXvn/6xd8hQ10qOQGVqrQ3iIffCgyG3M+v2OLVWzLxa1CQQbZFYOH5jihaKxN37Q3mrwUlSKU3vyFzrcRhbiuPDd32YZyWlAaoH0bl8+flVLMyMprw== bot@devolutions.net'
          sshPassphrase: $(SSH_AZP_PRIVATE_GITHUB_PASSPHRASE)
          sshKeySecureFile: ssh-azp-private-github

      - script: ./build.py -p ios --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: macOS
    pool:
      name: 'Devolutions - macOS'

    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDh1m1BXRO0oUWEsTt2THFUqN1v4wwaNdcfKpPTpS501150EPsCCcf7BS4aFwgYl/UYMRxmywqlwQwIjmkxqdNHejYXaBa4JMDFMinWAPKLueo8xQdfcgS1xhTGdqyGFsHtjGlJMe8oys3FtK06NL6JnFHrYzVr9aR4yhMDnQyHSEHrHj+uc0OzTKnmkiG4pP3IJfnj6/HS+zLdkqs28sTAouV1YGLK34SsspCy4R5wpOMkM/6/DItqFPvdMaAPMpD52YYzyYUOVy43X8XBbLQI2hzv2lFH0enNiY3UaGKYeDL4cxzbsIenc/4WtD1HvIX9apA2fbuGqfUrk2faHkR9P7A2Eo0sbt43SY4MKBrLXlYQVDd3SFbwoDVIWgVoqrPZJmJdzKOlXgKyB9oSYdHiJkmijBFno9PWeyuHeldmw+YjUkltyD5TEcDsNd98V/EC9Mq5zTrdd1Sbaw313jlyz0uhh/lbbI0aZy8/IQries0RHmxYvPMZc4ZZA+eEcaUtJZ8ABJLIO4I+6WX/YzNJvjSV41GbBiKigUG9OeOoW3uOuFNkTXmI8DL/MXvn/6xd8hQ10qOQGVqrQ3iIffCgyG3M+v2OLVWzLxa1CQQbZFYOH5jihaKxN37Q3mrwUlSKU3vyFzrcRhbiuPDd32YZyWlAaoH0bl8+flVLMyMprw== bot@devolutions.net'
          sshPassphrase: $(SSH_AZP_PRIVATE_GITHUB_PASSPHRASE)
          sshKeySecureFile: ssh-azp-private-github

      - script: ./build.py -p macos --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)

  - job: windows
    pool:
      name: 'Devolutions - Windows containers'

    workspace:
      clean: all

    container: devolutions/waykbuilder:vstools2k19

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDh1m1BXRO0oUWEsTt2THFUqN1v4wwaNdcfKpPTpS501150EPsCCcf7BS4aFwgYl/UYMRxmywqlwQwIjmkxqdNHejYXaBa4JMDFMinWAPKLueo8xQdfcgS1xhTGdqyGFsHtjGlJMe8oys3FtK06NL6JnFHrYzVr9aR4yhMDnQyHSEHrHj+uc0OzTKnmkiG4pP3IJfnj6/HS+zLdkqs28sTAouV1YGLK34SsspCy4R5wpOMkM/6/DItqFPvdMaAPMpD52YYzyYUOVy43X8XBbLQI2hzv2lFH0enNiY3UaGKYeDL4cxzbsIenc/4WtD1HvIX9apA2fbuGqfUrk2faHkR9P7A2Eo0sbt43SY4MKBrLXlYQVDd3SFbwoDVIWgVoqrPZJmJdzKOlXgKyB9oSYdHiJkmijBFno9PWeyuHeldmw+YjUkltyD5TEcDsNd98V/EC9Mq5zTrdd1Sbaw313jlyz0uhh/lbbI0aZy8/IQries0RHmxYvPMZc4ZZA+eEcaUtJZ8ABJLIO4I+6WX/YzNJvjSV41GbBiKigUG9OeOoW3uOuFNkTXmI8DL/MXvn/6xd8hQ10qOQGVqrQ3iIffCgyG3M+v2OLVWzLxa1CQQbZFYOH5jihaKxN37Q3mrwUlSKU3vyFzrcRhbiuPDd32YZyWlAaoH0bl8+flVLMyMprw== bot@devolutions.net'
          sshPassphrase: $(SSH_AZP_PRIVATE_GITHUB_PASSPHRASE)
          sshKeySecureFile: ssh-azp-private-github

      - script: C:\BuildTools\Common7\Tools\VsDevCmd.bat && python build.py -p windows --debug
        displayName: Running build.py
        env:
          CONAN_PASSWORD: $(CONAN_PASSWORD)
