name: conan packages
on: workflow_dispatch
jobs:
  build:
    name: conan packages [${{matrix.arch}}-${{matrix.os}}]
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86, x86_64, arm, aarch64 ]
        os: [ windows, macos, linux, ios, android ]

        exclude:
          - arch: x86
            os: macos
          - arch: x86
            os: linux
          - arch: x86
            os: ios
          - arch: arm
            os: windows
          - arch: arm
            os: macos
          - arch: arm
            os: linux

        include:
          - os: windows
            runner: windows-2019
          - os: macos
            runner: macos-latest
          - os: linux
            runner: ubuntu-18.04
          - os: ios
            runner: macos-latest
          - os: android
            runner: ubuntu-20.04
            
    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: runner.os == 'Linux'

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        if: runner.os == 'Linux'

      - name: Configure Windows runner
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install --no-progress ninja
          choco install --no-progress cmake
          choco install --no-progress 7zip
          choco install --no-progress python
          choco install --no-progress vswhere
          choco install --no-progress nasm yasm
          pip install conan==1.40.0 invoke Jinja2 urllib3 chardet requests --upgrade
          iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -Quiet"
          echo $PSVersionTable
          echo "CONAN_USER_HOME=C:/tmp" >> $Env:GITHUB_ENV

      - name: Configure macOS runner
        if: runner.os == 'macOS'
        env:
          CMAKE_OSX_DEPLOYMENT_TARGET: "10.12"
        run: |
          brew install ninja
          brew install cmake
          brew install python
          brew install nasm yasm
          pip3 install conan==1.40.0 invoke Jinja2 urllib3 chardet requests --upgrade
          brew install --cask powershell
          sudo rm -rf /Library/Developer/CommandLineTools
          echo "CONAN_USER_HOME=/tmp" >> $GITHUB_ENV

      - name: Configure Linux runner
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ninja-build
          sudo apt install cmake
          sudo apt install xz-utils
          sudo apt install nasm yasm
          sudo apt install python3 python3-pip python3-wget python3-setuptools
          pip3 install conan==1.40.0 invoke Jinja2 urllib3 chardet requests --upgrade
          bash <(wget -qO - https://aka.ms/install-powershell.sh)
          echo "CONAN_USER_HOME=/tmp" >> $GITHUB_ENV

      - name: Install clang+llvm
        if: runner.os == 'Linux'
        run: |
          CLANG_LLVM_OS="ubuntu-$(lsb_release -rs)"
          CLANG_LLVM_BASE_URL="https://github.com/awakecoding/llvm-prebuilt/releases/download/v2021.2.4"
          CLANG_LLVM_NAME="clang+llvm-12.0.1-x86_64-${CLANG_LLVM_OS}"
          wget -q "${CLANG_LLVM_BASE_URL}/${CLANG_LLVM_NAME}.tar.xz"
          tar -xf "${CLANG_LLVM_NAME}.tar.xz" -C /tmp
          sudo mv "/tmp/${CLANG_LLVM_NAME}" /opt/llvm
          echo "PATH=$PATH:/opt/llvm/bin" >> $GITHUB_ENV

      - name: Install Android NDK
        if: matrix.os == 'android'
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip -q android-ndk-r21e-linux-x86_64.zip -d /tmp
          sudo mv /tmp/android-ndk-r21e /opt/android-ndk
          echo "ANDROID_NDK=/opt/android-ndk" >> $GITHUB_ENV

      - name: Configure conan environment
        shell: pwsh
        run: |
          conan config init
          conan config install ./settings
          $ConanManifestTime = $(git log -1 --pretty=format:%ct)
          echo "CONAN_MANIFEST_TIME=$ConanManifestTime" >> $Env:GITHUB_ENV

      - name: Build conan packages
        run: |
          pwsh build.ps1 -Platform ${{matrix.os}} -Architecture ${{matrix.arch}} -BuildType Both

      - name: Package conan cache
        shell: pwsh
        run: |
          $PACKAGE_NAME="conan-${{matrix.arch}}-${{matrix.os}}"
          conan remove --locks
          $CONAN_DATA = Join-Path $Env:CONAN_USER_HOME ".conan" "data"
          $RemoveList = Get-ChildItem "${CONAN_DATA}" -Include @("build","source") -Directory -Depth 4 -Recurse -Name
          $RemoveList | ForEach-Object { Remove-Item -Path "$CONAN_DATA/$_" -Recurse -Force }
          $ConanManifests = Get-ChildItem $CONAN_DATA -Recurse -Include "conanmanifest.txt"
          $ConanManifestTime = $Env:CONAN_MANIFEST_TIME
          foreach ($ManifestFile in $ConanManifests) {
            $Manifest = Get-Content $ManifestFile
            $Manifest[0] = $ConanManifestTime
            $Manifest | Out-File $ManifestFile
          }
          tar -czf "${PACKAGE_NAME}.tar.gz" -C "$Env:CONAN_USER_HOME" ".conan"

      - name: Upload conan cache
        uses: actions/upload-artifact@v2
        with:
          name: conan-${{matrix.arch}}-${{matrix.os}}
          path: conan-${{matrix.arch}}-${{matrix.os}}.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Configure runner
        run: |
          sudo apt update
          sudo apt install python3 python3-pip python3-wget python3-setuptools
          pip3 install conan==1.40.0 invoke Jinja2 urllib3 chardet requests --upgrade
          bash <(wget -qO - https://aka.ms/install-powershell.sh)
          echo "CONAN_USER_HOME=/tmp" >> $GITHUB_ENV

      - name: Configure conan environment
        run: |
          conan config init
          conan config install ./settings

      - name: Download conan data
        uses: actions/download-artifact@v2
        with:
          path: download

      - name: Publish conan data
        working-directory: download
        shell: pwsh
        run: |
          $Env:CONAN_REMOTE_NAME="devolutions-public"
          $Env:CONAN_REMOTE_URL="https://conan.cloudsmith.io/devolutions/conan-public"
          $Env:CONAN_LOGIN_USERNAME="${{ secrets.CLOUDSMITH_CONAN_PUBLIC_USERNAME }}"
          $Env:CONAN_PASSWORD="${{ secrets.CLOUDSMITH_CONAN_PUBLIC_PASSWORD }}"
