name: conan packages
on: workflow_dispatch
jobs:
  build:
    name: conan packages [${{matrix.arch}}-${{matrix.os}}]
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64 ]
        os: [ windows, macos, linux ]

        include:
          - os: windows
            runner: windows-2019
          - os: macos
            runner: macos-10.15
          - os: linux
            runner: ubuntu-18.04
    steps:
      - name: Configure Windows runner
        if: runner.os == 'Windows'
        run: |
          choco install --no-progress ninja cmake 7zip
          choco install --no-progress python
          choco install --no-progress vswhere
          choco install --no-progress nasm yasm
          pip install conan==1.39.0 conan_package_tools==0.35.1 invoke Jinja2 pywin32 --upgrade
          iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -Quiet"

      - name: Configure macOS runner
        if: runner.os == 'macOS'
        env:
          CMAKE_OSX_DEPLOYMENT_TARGET: "10.12"
        run: |
          brew install ninja cmake
          brew install python
          brew install --cask powershell

      - name: Configure Linux runner
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ninja-build cmake xz-utils
          sudo apt install python3 python3-pip python3-wget
          sudo apt install nasm yasm
          pip3 install --user conan==1.39.0 conan_package_tools==0.35.1 invoke Jinja2 --upgrade
          bash <(wget -qO - https://aka.ms/install-powershell.sh)

      - name: Configure conan settings
        run: |
          conan config install ./settings

      - name: Build conan packages
        run: |
          pwsh build.ps1
