name: conan publish
on: workflow_dispatch
  inputs:
    runId:
      description: 'run id'     
      required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Configure runner
        run: |
          sudo apt update
          sudo apt install python3 python3-pip python3-wget python3-setuptools
          pip3 install conan==1.40.0 invoke Jinja2 urllib3 chardet requests --upgrade
          bash <(wget -qO - https://aka.ms/install-powershell.sh)
          echo "CONAN_USER_HOME=/tmp" >> $GITHUB_ENV

      - name: Configure conan environment
        run: |
          conan config init
          conan config install ./settings

      - name: Download conan data
        uses: actions/download-artifact@v2
        with:
          workflow: ${{ github.event.inputs.runId }}
          path: download

      - name: Publish packages
        working-directory: download
        shell: pwsh
        env:
          CONAN_REMOTE_NAME: "artifactory"
          CONAN_REMOTE_URL: "https://devolutions.jfrog.io/devolutions/api/conan/conan-local"
        run: |
          ../publish.ps1 -ConanUsername ${{ secrets.ARTIFACTORY_USERNAME }} -ConanPassword ${{ secrets.ARTIFACTORY_PASSWORD }}
